### ISSUE TITLE
Cannot read properties of null (reading 'setRoot')

### ISSUE THREAD

**Issue by grassick** [schrodinger/fixed-data-table-2#661] opened 2022-12-02 16:50 UTC
## Expected Behavior
Table should not cause exception when being unmounted

## Current Behavior
Table sometimes (and I mean sometimes, seems to be a difficult to reproduce race condition) throws exception `Cannot read properties of null (reading 'setRoot')` in FixedDataTable in the `_onRef` function, as `_wheelHandler` is already null by the time it's called. This is because of componentWillUnmount being called before the div is de-refed.

## Possible Solution
Check that `this._wheelHandler` isn't null

## Steps to Reproduce (for bugs)
I really wish I could. It's been working fine for years in our code and just started blowing up today. I can't even get it to happen consistently on a repo.

## Context
It makes our product crash. It's bad.

## Your Environment
* Version used: 1.2.13
* Browser Name and version: Chrome Version 107.0.5304.121 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Linux
* Link to your project: N/A

**Comment by pradeepnschrodinger** [comment] 2022-12-03 21:43
Thanks for brining the issue to our attention.

The NPE seen here comes from the changes made by #657 that I merged a couple of days back, which was (ironically) meant to fix a similar NPE.
I can reproduce the error consistently by mounting and then unmounting the table. 

I'll take a look at the PR, thanks!

**Comment by pradeepnschrodinger** [comment] 2022-12-03 21:48
> The NPE seen here comes from the changes made by https://github.com/schrodinger/fixed-data-table-2/pull/657 that I merged a couple of days back

Nvm, this is only partially true. The issue always existed before #657, although it was only seen when `stopReactWheelPropagation` is set to true. 
#657 has just brought the error up consistently on unmounting regardless of the value for `stopReactWheelPropagation`.

**Comment by pradeepnschrodinger** [comment] 2022-12-03 23:51
The fix for this is available on [v1.2.14](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v1.2.14), through #664.

**Comment by pradeepnschrodinger** [comment] 2022-12-04 00:00
I'm closing this off since the issue is resolved, but feel free to comment/reopen if you need any help or have any questions.

**Closed by pradeepnschrodinger** 2022-12-04 00:00 UTC
Labels: bug, regression
