### ISSUE TITLE
what is best way to prevent whole page scrolling when table is scrolling up?

### ISSUE THREAD

**Issue by datavisorfrankhe** [schrodinger/fixed-data-table-2#419] opened 2019-03-27 21:59 UTC
I found that when table is scrolling up, the whole page containing the table keeps scrolling up also. Can I ask what is the best way to prevent out div wrapper from scrolling up when the table is scrolling, even if it has already scrolled to the end?

I tried the onScrollStartEvent, I want to have the native event, and then use event.preventPropotation, but I can not get the native scrolling event from this event. 

Any ideal will be helpful.

Thanks

## Your Environment

* Version used: 
"react": "15.3.2",
"fixed-data-table-2": "^0.8.13",

* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by wcjordan** [comment] 2019-03-28 13:24
I suspect this is caused by #407.  Feel free to try out the proposed changes to fix the issue mentioned there and let me know how it goes.

**Comment by pradeepnschrodinger** [comment] 2019-04-03 02:34
@datavisorfrankhe, I think this might be due to our `onWheel` handler not calling [`preventDefault` if there's no apparent scrolling](https://github.com/schrodinger/fixed-data-table-2/blob/master/src/vendor_upstream/dom/ReactWheelHandler.js#L98). Basically this call is skipped if there's no scroll to be done, which happens if you scroll up when the table is already at top position.

@wcjordan , we'll put a quick PR for this?

**Comment by wcjordan** [comment] 2019-04-03 14:10
Hmm I actually think that would be expected behavior.  If you scroll to the top of the grid and continue to scroll up, it should scroll the page up.  For an example of what I mean, play around with the scrollable grid content here: https://www.ag-grid.com/example-gallery/#example-auto-height-full-width

**Comment by datavisorfrankhe** [comment] 2019-04-03 15:10
I suggest not scrolling the whole page even if user scrolled to the top of
the grid. what's other people's opinion?
Or can we put a flag to control this?

**Comment by wcjordan** [comment] 2019-04-03 15:11
A flag seems like a reasonable approach.

**Comment by pradeepnschrodinger** [comment] 2019-04-04 23:16
@datavisorfrankhe, issue fixed with release [v1.0.0-beta.16](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v1.0.0-beta.16).
You need to pass the flag `stopScrollDefaultHandling` with `true` so that the page is never scrolled up while scrolling in the table.

I'll close the issue for now, but feel free to reopen if you face any issues.

**Closed by pradeepnschrodinger** 2019-04-04 23:16 UTC
