### ISSUE TITLE
Resizing of Columns with flexGrow

### ISSUE THREAD

**Issue by skekec** [schrodinger/fixed-data-table-2#281] opened 2018-01-20 11:48 UTC
Resizing of columns which has the flexGrow property is really confusing. Expanding seems to be ok but reducing does not work at all. 
## Expected Behavior

Resizing should work like in scenarios without flexGrow.
## Possible Solution

Maybe it is a good idea to calculate the column widths only on initial rendering based on the total width of the table and set it in the width property. Resizing should work then. Otherwise the table try to recover its column sizes again.
## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by wcjordan** [comment] 2018-01-21 12:44
You're right these features definitely don't work together.  I'd be happy to accept a PR to fix.  I'm not sure your proposed solution will work, since I suspect it would result in issues when the table container is resized as the columns would no longer grow to fill the space.

**Comment by alvaro1728** [comment] 2018-02-07 20:51
I tested this without the flexGrow property in my column definitions and the problem still occurs.  When I resize a column, I get a blue vertical line that I can drag left or right but when I let it go, nothing happens -- the line stays there and the columns aren't resized.  I just upgraded to v0.8.10.

Thanks,
Alvaro

**Comment by wcjordan** [comment] 2018-02-07 22:02
@alvaro1728  could you file a separate issue with a JsFiddle or CodePen for reproduction.  I suspect you haven't hooked up the resize handlers properly but I don't want to conflate with this issue.  Thanks

**Comment by alvaro1728** [comment] 2018-02-08 22:06
@wcjordan your message led me back to your column resizing example where I noticed that sure enough, I wasn't providing a onColumnResizeEndCallback handler.  I didn't know I had to.  So after adding it, resizing is working for me.  Thanks.

**Comment by wcjordan** [comment] 2020-05-04 18:04
closing as seems to have been a misunderstanding w/ our (poorly working) API.

**Closed by wcjordan** 2020-05-04 18:04 UTC
Labels: bug, help wanted
