### ISSUE TITLE
Header row lost : if keep pressing tab and scroll take place in grid

### ISSUE THREAD

**Issue by projesh** [schrodinger/fixed-data-table-2#429] opened 2019-04-12 11:14 UTC
## While tabbing scroll take place and HEAD BAR get lost ( my issue )

* No idea how to solve it. 
* Working on old project with Fix-Data-Table-2

**Comment by wcjordan** [comment] 2019-04-12 15:10
This is a duplicate of #152, so I'm going to close it.  Feel free to read that issue and continue the conversation there.  There's a description of ideas across #152 & #149 which may help if you want to attempt a fix and create a PR.

**Closed by wcjordan** 2019-04-12 15:10 UTC
