### ISSUE TITLE
vertical scroll missing when dynamic data exceeds viewport

### ISSUE THREAD

**Issue by moraleslos** [schrodinger/fixed-data-table-2#136] opened 2017-03-30 20:36 UTC
Just switched over to this data table and everything seems to be working.  Only issue I have is that my data table will initially have no data (0 records) and when a user performs a lookup, my app will populate this data table with records.  I can see the records displayed just fine in the data table however there is no vertical scrollbar to "notify" the user there are more records than what is currently shown.  I can scroll up and down ok in the data table using the wheel of my mouse but it would be nice to show a scroll bar as well.  I see in the examples the scrollbar working but I assume it shows only on initial load.  

Any help would be appreciated.

**Comment by KamranAsif** [comment] 2017-04-03 13:28
Can you reproduce this in a jsfiddle?

**Comment by KamranAsif** [comment] 2017-04-30 14:45
Closing, since theres no follow up

**Closed by KamranAsif** 2017-04-30 14:45 UTC
