### ISSUE TITLE
bigData cell merge 

### ISSUE THREAD

**Issue by whizbz11** [schrodinger/fixed-data-table-2#498] opened 2019-10-28 07:26 UTC
Table with merged cells, blank when scrolling
![image](https://user-images.githubusercontent.com/13316317/67659333-058cc400-f997-11e9-8114-abce922cfc06.png)

## Expected Behavior
Don't want to see blanks when the table scrolls

## Your Environment

* Version used:V1.0.0
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): 78.0.3904.70
* Link to your project:

**Comment by pradeepnschrodinger** [comment] 2019-10-31 07:57
FDT doesn't support merged cells natively, so this seems like either the cell renderers were customized or you might be working on a forked version of FDT.

A reproducible codepen link would be really helpful here.

**Comment by wcjordan** [comment] 2019-11-11 19:37
Closing due to inactivity

**Closed by wcjordan** 2019-11-11 19:37 UTC
