### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property '__TableColumnGroup__' of undefined(…)

### ISSUE THREAD

**Issue by hyalkaf** [schrodinger/fixed-data-table-2#95] opened 2016-12-07 19:36 UTC
I have been using fixed-data-table successfully but lately after fixing lots of linting errors, I started getting this error: `Uncaught (in promise) TypeError: Cannot read property '__TableColumnGroup__' of undefined`. I'm not sure what is going on as the code in my component seems to be fine. The error is thrown in the library code which makes me think that the error is in my code somewhere else. 

Here is the code that is related to fixed data table:

```
import React, { PropTypes } from 'react';
import { Table, Column, Cell } from 'fixed-data-table-2';
import { TextCell } from './CellComponents.jsx';
import { createDynamicComponentForCells } from './UtilityFunctions.jsx';

class TableComp extends React.Component {
  render() {
    return (
      <Table
        height={this.props.heightFactor}
        width={this.props.widthFactor}
        rowsCount={this.props.data.length}
        rowHeight={this.props.rowHeight}
        headerHeight={this.props.headerHeight}
        style={null}
      >

        { Object.keys(this.props.data
          .reduce((val1, val2) => Object
            .assign({}, val1, val2), {}) || {})
        .map((field, index) => {
          let CellComponent;
          let widthCell;
          if (this.props.mapDataToCellComponentName === undefined) {
            CellComponent = <TextCell style={null} data={this.props.data} col={field} />;
          } else {
            const [component, decimalPlaces, width] = this.props
            .mapDataToCellComponentName(field, index);
            widthCell = width;
            /*CellComponent = createDynamicComponentForCells(component,
              { style: null,
                data: this.props.data,
                col: field,
                decimals: decimalPlaces
              }
            );*/
          }
          return (<Column
            style={null}
            key={field}
            cell={<Cell>ji</Cell>}
            header={
              <Cell
                width={widthCell !== undefined ? widthCell :
                  this.props.columnWidth}
              >{field}</Cell>
            }
            width={widthCell !== undefined ? widthCell : this.props.columnWidth}
          />
          );
        })
        };
      </Table>
    );
  }
}

TableComp.propTypes = {
  data: PropTypes.array.isRequired,
  mapDataToCellComponentName: PropTypes.func,
  heightFactor: PropTypes.number.isRequired,
  widthFactor: PropTypes.number.isRequired,
  rowHeight: PropTypes.number.isRequired,
  headerHeight: PropTypes.number.isRequired,
  columnWidth: PropTypes.number.isRequired
};

export default TableComp;
```

As you can see, I'm trying to render the simplest cells inside Column since I want to see if it's working or not. It used to have custom cells. 

Here is the error stack trace:

![stack trace](https://cloud.githubusercontent.com/assets/5642132/20983450/cafb7f82-bc79-11e6-96fc-1dc0705e8f7e.PNG)

* Version used: **"fixed-data-table-2": "^0.7.7"**
* Browser Name and version: electron with react and redux
* Operating System and version (desktop or mobile): windows 10 PC

**Comment by KamranAsif** [comment] 2016-12-07 19:53
Hey,

That error means your not passing in correct children elements under the Table component.
Can you get your code working on jsfiddle? It's a bit hard to debug as its currently written

**Comment by hyalkaf** [comment] 2016-12-07 21:09
Thank you. I just rolled back to previous commit when the code was working and worked from there and now it's working. I will post what the error is once I compare the two codes. Thank you.

**Comment by KamranAsif** [comment] 2016-12-19 19:17
Closing this since there hasn't been any discussion. Feel free to re-open once you've got it reproducible

**Closed by KamranAsif** 2016-12-19 19:17 UTC
