### ISSUE TITLE
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive

### ISSUE THREAD

**Issue by datavisorfrankhe** [schrodinger/fixed-data-table-2#420] opened 2019-03-27 22:01 UTC
I noticed that this issue start happening whenever we scroll the table.
Chrome is throwing this error:
`[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive`

Are there any best solution for this?

Thanks

## Your Environment

* Version used:
"fixed-data-table-2": "^0.8.13",
"react": "15.3.2",

* Browser Name and version:
Version 73.0.3683.86 (Official Build) (64-bit)

* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by bodyflex** [comment] 2019-03-28 11:52
this started happening in Chrome 73: https://www.chromestatus.com/features/6662647093133312

basically the `wheel` event is now passive by default, so would have to explicitly add `{ passive: false }` to all wheel listeners. didn't find any in this project though, it's probably in some dependency...

**Comment by wcjordan** [comment] 2019-03-28 13:23
This is a dupe of #407.  Let's keep the conversation there.  There's a proposed fix which should work there if you're interested in trying it out on a fork and creating a pull request.

**Closed by wcjordan** 2019-03-28 13:23 UTC
