### ISSUE TITLE
Dispatching in onScrollStart causes onScrollEnd to fire

### ISSUE THREAD

**Issue by stevengoldberg** [schrodinger/fixed-data-table-2#288] opened 2018-01-31 23:02 UTC
## Expected Behavior
Using `redux`:
* `connect` to state in the `<Table>`'s parent
* Pass action creators to `<Table>`'s `onScrollStart` and `onScrollEnd`
* When the user scrolls the table, `onScrollStart` gets fired once when the user begins scrolling, and dispatches an action
* `onScrollEnd` gets fired once when the user finished scrolling, and dispatches an action

## Current Behavior
Using `redux`:
* `connect` to state in the `<Table>`'s parent
* Pass action creators to `<Table>`'s `onScrollStart` and `onScrollEnd`
* When the user scrolls the table, `onScrollStart` gets fired and dispatches an action creator. This causes the parent's props to update;  `componentWillReceiveProps` triggers [_didScrollStopSync](https://github.com/schrodinger/fixed-data-table-2/blob/master/src/FixedDataTable.js#L596); `_didScrollStopSync` triggers [onScrollEnd](https://github.com/schrodinger/fixed-data-table-2/blob/master/src/FixedDataTable.js#L1499).
* Thus, every time the user scrolls, we get a constant series of `SCROLL_START` and `SCROLL_END` events, which kills scroll performance and makes those events useless.

## Context
* We depend on the actions dispatched by `onScrollStart` and `onScrollEnd` to show/hide various elements on the page, and to only be fired at the appropriate times

## Your Environment
* Version used: 0.7.3
* Browser Name and version: Chrome 63.0.3239.132
* Operating System and version (desktop or mobile): Mac OSX 10.3.2

**Comment by wcjordan** [comment] 2018-02-06 12:20
@KamranAsif do you have any extra insight here.  I think this is just the behavior as designed, and you may want to update your use case to not modify props onScrollStop.

**Comment by KamranAsif** [comment] 2018-02-06 14:03
Might be easier to debug with a jsfiddle, but I think this is intended behavior. Right now the table doesn't handle shallow props changing so it thinks the table was updated, and ends the scroll right away.

**Comment by wcjordan** [comment] 2018-02-06 14:05
I don't think we can fix without a major bump, but do you think we could get away moving the stop scroll into the if statement of the start scroll on v1?

**Comment by KamranAsif** [comment] 2018-02-11 21:45
@wcjordan That seems like a hacky fix. I would not advise

**Comment by wcjordan** [comment] 2018-02-12 05:33
Could you elaborate, @KamranAsif?  My assumption is we stop scroll in componentWillReceiveProps because we start scroll there.  But the start scroll is in a conditional, while the stop scroll is called always.  Do you have any deeper detail on why we'd need to stop scroll always.

**Comment by wcjordan** [comment] 2018-03-06 22:25
@KamranAsif ping on the miscommunication / additional details above.

**Comment by KamranAsif** [comment] 2018-03-08 15:32
Sorry for late response; the solution does not seem idiomatic. The real bug is that omponentWillReceiveProps is triggering _didScrollStopSync;

**Comment by wcjordan** [comment] 2018-03-09 17:16
My read of this is componentWillRecieveProps can change the scroll position through controlled scrolling.  In these cases we trigger the scroll start and scroll stop callbacks to notify the owner that the grid has scrolled.  I assume anytime we trigger scroll start, we want a corresponding scroll stop when the scrolling ends.

So there are 2 ways we could go here:
1) Only trigger scroll stop if we trigger scroll start by moving into the if statement.  This would fix the infinite triggering reported here.
2) Don't trigger scroll start or stop from componentWillRecieveProps, and let the owner handle the controlled scroll.  This would be a breaking API change, but may force cleaner data flow.

Kam, it sounds like you're in favor of 2, but I'm still not clear on the benefits over 1 and why forcing that owner to handle controlled scrolls differently is a best practice.

**Comment by pradeepnschrodinger** [comment] 2019-10-10 07:39
Closing as the issue mentioned by OP no longer exists as of [v1.0.0](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v1.0.0) (due to #398). 

I think it's better to open up a new issue/PR to discuss anything more, if needed ofc.

**Closed by pradeepnschrodinger** 2019-10-10 07:39 UTC
