### ISSUE TITLE
React 18 question

### ISSUE THREAD

**Issue by haskic** [schrodinger/fixed-data-table-2#668] opened 2022-12-18 16:33 UTC
I've migrated my project to React 18 and faced with some table scrolling issue.
For some reason scrolling is slow (scroller not able to keep up with my mouse), if we are using root.render.
ReactDOM.render works fast as expected.

## Your Environment

* Version used: 1.2.15
* Browser Name and version: Chrome 108.0.5359.125
* Link to your project:  https://codesandbox.io/s/billowing-star-otk3b5

**Comment by pradeepnschrodinger** [comment] 2023-01-09 11:05
Thank you for filing this along with a reproducible sandbox.

I'm not totally sure on why this bug exists, and that only when using React's `createRoot` API, but my hunch would be on https://github.com/reactwg/react-18/discussions/21#:~:text=if%20it%20doesn%27t!)-,Does%20this%20break%20anything%20for%20Classes%3F,-Keep%20in%20mind.

The code in our scrollbar components or scroll handlers _might_ be assuming that state updates are not batched. This was a reasonable assumption until clients use React's new `createRoot` api, which turns on automatic batching for state updates.

Ofc, we'll need to dig more into this to confirm, but some starting points for us would be to investigate code around the [custom ScrollBar](https://github.com/schrodinger/fixed-data-table-2/blob/v1.2.x/src/plugins/Scrollbar.js#L422) component and associated [scroll handlers](https://github.com/schrodinger/fixed-data-table-2/blob/v1.2.x/src/vendor_upstream/dom/DOMMouseMoveTracker.js#L167).

**Comment by Catsbe** [comment] 2023-01-12 03:00
Same problem，Hope fix this as soon as possible

**Comment by pradeepnschrodinger** [comment] 2023-01-19 20:05
Hey, just wanted to leave an update.

I haven't identified the root cause yet, but have figured out a workaround.
I've verified locally that the using the `flushSync` react-dom API to immediately flush this [setState call](https://github.com/schrodinger/fixed-data-table-2/blob/v1.2.x/src/plugins/Scrollbar.js#L422) in our scroll component fixes the issue. 
So our initial assumption around React 18 batching scrollbar updates was right (probably).

For now I've put this fix under PR #672, which should get merged to v1.2 in a couple of days.

**Comment by pradeepnschrodinger** [comment] 2023-01-25 10:39
@haskic , @Catsbe , this is now fixed through [v1.2.16](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v1.2.16).

I'm closing off the issue, but feel free to continue the discussion if you got any questions or run into trouble.

**Closed by pradeepnschrodinger** 2023-01-25 10:39 UTC
Labels: bug, help wanted
