### ISSUE TITLE
Typing into truncated input box causes row to shift.

### ISSUE THREAD

**Issue by SimonChris** [schrodinger/fixed-data-table-2#470] opened 2019-06-24 15:57 UTC
**Bug Report**

**Steps to reproduce**
Make a table with a cell containing a text input spanning the width of the cell, somewhere in the right side of the table.

Decrease the window size, so that the input box is only partially visible in the browser.

Type into the input box, until the text leaves the side of the window.

**Result**
The entire row shifts to the left, causing it to be unaligned with the remaining rows.

Increasing the size of the window does not cause the row to move back.

![TableError](https://user-images.githubusercontent.com/7115907/60033799-8c5c2800-96a9-11e9-915e-94b0ee768a0b.png)

**Comment by wcjordan** [comment] 2019-06-28 18:31
Unfortunately this is a known issue and a duplicate of #152 (& #149). Those issues describe this in more detail as well as a possible solution. I'd accept a PR for that solution, but I believe it would be a fair amount of work (although there are some POCs you could build on).

For our application, we've worked around this instead by making our cells spans by default and only making them inputs when clicked. We also prevent inputs from scrolling off screen, either by locking scroll while a cell is being edited or exiting edit mode when a cell scrolls off screen.

I'm going to close as a duplicate, but feel free to continue the conversation on #152

**Closed by wcjordan** 2019-06-28 18:31 UTC

**Comment by SimonChris** [comment] 2019-06-29 15:03
Thanks for the reply. How do you lock scroll while editing a cell?

**Comment by wcjordan** [comment] 2019-06-29 15:18
We use the libraries scrollTop and scrollLeft APIs to control scrolling.
