### ISSUE TITLE
Cannot scroll down till the last row with in-built vertical scroller

### ISSUE THREAD

**Issue by amit1911** [schrodinger/fixed-data-table-2#69] opened 2016-10-21 09:49 UTC
## Expected Behavior

If new content is added to the table and I drag the vertical scroller down, then I should be able to view all the content.
## Current Behavior

After new content is added in the table, the scroller appears but when you drag it down, you cannot see some of the new content. Whereas if you scroll inside the table (without dragging the in-built scroller), then you can see all the content. 
## Steps to Reproduce (for bugs)

https://jsfiddle.net/amit1911/34k8uf8o/
## Context

I have a table with **pagination** and **change records per page** feature. When users switch from let's say 10 records/page to 100 records/page then they should be able to scroll and view all the new rows. So right now when users drag the in-built scroller down to view new records, they are not able to scroll down to the last record. A couple of records become inaccessible. But if you just scroll down inside the table (without dragging down the in-built scroller), then you can view all the records.
## Your Environment
- Version used: 0.7.6
- Browser Name and version: Chrome and Firefox (latest)
- Operating System and version (desktop or mobile): Windows 7 64-bit

**Comment by KamranAsif** [comment] 2016-10-24 13:37
This is a known issue, duplicate of https://github.com/schrodinger/fixed-data-table-2/issues/9 and https://github.com/schrodinger/fixed-data-table-2/issues/25

Not sure when we are going to get back to https://github.com/schrodinger/fixed-data-table-2/pull/42 but the targeted fix is 0.8

**Comment by wcjordan** [comment] 2016-10-24 14:03
I'm not sure I'd consider it a duplicate since those only affect dynamic row heights, while this one doesn't seem to.  @KamranAsif do you have more detail on what's happening here and why it occurs?

I thought it would be more related to the oversized divs issue (https://github.com/schrodinger/fixed-data-table-2/issues/67), but didn't get a chance to research it.

**Comment by KamranAsif** [comment] 2016-10-24 14:04
@wcjordan His example does have dynamic row heights. Check out rowHeightGetter in his ResizeTable calss

**Comment by amit1911** [comment] 2016-10-25 06:58
@KamranAsif is there any workaround for this till you release 0.8? I really need to fix this issue.

**Comment by wcjordan** [comment] 2016-11-06 21:44
Hey @amit1911 I don't think we have a good way to support dynamic rows at this time.  We do have some example PRs where we're trying to cleanup towards a 0.8 release.  Sorry we don't have a better response for you.

**Comment by amit1911** [comment] 2016-11-07 02:49
@wcjordan thanks anyway. i changed to fixed row height for now. Using ellipsis and tooltip for cases that require extra height.

**Comment by KamranAsif** [comment] 2016-11-16 18:08
Closing this as duplicate

**Closed by KamranAsif** 2016-11-16 18:08 UTC
Labels: duplicate
