### ISSUE TITLE
Filtering and Column sorting in not working

### ISSUE THREAD

**Issue by dspoonia7** [schrodinger/fixed-data-table-2#43] opened 2016-08-14 08:40 UTC
Initially Table is rendering successfully and scrolling works fine. But on filtering or column sorting, I am getting this error

> Uncaught Error: Invariant Violation: Index out of range 0

After getting this error, Scrolling also stops working and throws the same error.

I am on the latest version of react and fixed-data-table and using es6 classes.

``
    "fixed-data-table-2": "^0.7.2",
    "react": "^15.3.0",
    "react-dom": "^15.3.0"
``

**Comment by KamranAsif** [comment] 2016-08-14 14:02
We don't support native filtering or sorting. Where are you seeing this error?
Please provide a jsfiddle to reproduce this issue. You can fork: https://jsfiddle.net/uq8osbp1/

**Comment by dspoonia7** [comment] 2016-08-14 14:08
I had tried [Filtering](http://schrodinger.github.io/fixed-data-table-2/example-sort.html) and [Sorting](https://github.com/schrodinger/fixed-data-table-2/blob/master/examples/SortExample.js) these examples only.

**Comment by wcjordan** [comment] 2016-08-14 15:52
Are you able to see the errors [here](http://schrodinger.github.io/fixed-data-table-2/example-sort.html)?  If not then the issue may be something related to React 15.3.0.  Could you try 15.1.0 and see if it works around the issue temporarily?

**Comment by dspoonia7** [comment] 2016-08-14 18:35
@wcjordan That doesn't help. On filter search, I am still getting 

> Uncaught Error: Invariant Violation: Index out of range 0

But on sorting it started throwing

> Uncaught TypeError: Cannot read property 'releaseMouseMoves' of undefined

Here is my [code](https://gist.github.com/dspoonia7/b157c5dc7b4464b743333b31af3e4c55)

package.json

```
  "dependencies": {
    "babel-plugin-transform-class-properties": "^6.11.5",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-es2015": "^6.9.0",
    "babelify": "^7.3.0",
    "browserify": "^13.1.0",
    "browserify-incremental": "^3.1.1",
    "fixed-data-table-2": "^0.7.2",
    "jquery": "^3.1.0",
    "jquery-ujs": "^1.2.1",
    "react": "^15.1.0",
    "react-dom": "^15.1.0"
  },
  "devDependencies": {
    "babel-polyfill": "^6.13.0",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.11.1",
    "babel-preset-stage-2": "^6.13.0"
  },
```

**Comment by wcjordan** [comment] 2016-08-14 18:38
Interesting, were you able to see the same issue on the hosted demos I linked?

**Comment by dspoonia7** [comment] 2016-08-14 19:05
No that is working fine.

**Comment by wcjordan** [comment] 2016-08-14 19:23
Would it be possible to create a github repo which reproduces your issue?  That will make it easier to investigate and debug.

**Comment by dspoonia7** [comment] 2016-08-14 20:24
@KamranAsif @wcjordan Here is the [fiddle](https://jsfiddle.net/dspoonia7/uq8osbp1/2/)
Fix column is also not working.

**Comment by wcjordan** [comment] 2016-08-15 04:52
It seems your fiddle has a few issues.  this._dataList and this._defaultSortIndexes become out of date in DataTable since they are not updated in componentWillReceiveProps.  I was able to fix that, but then started seeing undefineds in DateCell.  Could you investigate and let us know when the bugs are worked out?

**Comment by dspoonia7** [comment] 2016-08-15 13:48
Thanks guys,  I fixed all the issues in the fiddle at least. updated [fiddle](https://jsfiddle.net/dspoonia7/uq8osbp1/5/).

But in my local i am still getting this error sometimes 
> Uncaught TypeError: Cannot read property 'releaseMouseMoves' of undefined

**Comment by KamranAsif** [comment] 2016-08-15 13:53
How are you reproducing that releaseMouseMoves? I tried playing around with it but I'm not seeing any error.

What browser are you using?

**Comment by dspoonia7** [comment] 2016-08-15 14:03
Yes there is no issue in fiddle, it is working alright.

I am getting that error in my local system . I am using Chrome and I have setup rails-react-browserify.

One more issue, I have added [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en) extension in my browser. With this extension everything is working fine but on removing/disabling this extension, I am getting this error (and page is rendering totaly blank)
> Uncaught RangeError: Maximum call stack size exceeded

No clue what is happening here :(

**Comment by KamranAsif** [comment] 2016-08-15 14:09
Don't think we can help you there since its not related to FDT. 
I'm going to close this issue, but if you can get it reproducible on a fiddle, feel free to re-open it.

**Closed by KamranAsif** 2016-08-15 14:09 UTC
Labels: question
