### ISSUE TITLE
Table columns resizing loses state on parent re-render

### ISSUE THREAD

**Issue by alinvdumitru** [schrodinger/fixed-data-table-2#139] opened 2017-04-06 11:37 UTC
##Description
We usually update our table data often and thus re-render the parent component of fixed-data-table. When updating the table the resize bar is lost and user has to try it again. It's almost impossible to resize for real-time data flowing.

## Expected Behavior
Resize blue bar should be kept on updates & resizing data calculated correctly.

## Possible Solution
We always send ```isColumnResizing``` false from parent component because it seems like ```columnResizingData``` is always calculated based on ```nextProps```. We had the same for ```isColumnReordering``` but reordering data is only calculated based on old state in fixed-data-table. We successfully remove it but still struggle with column resizing. Tried to remove the property but resizing data is always lost. Maintaining a state in our parent component is impossible since there is no callback for ```columnResizing``` that can be sent.

A possible solution would be to calculate if column is resizing based on oldState rather than on nextProps.

## Steps to Reproduce (for bugs)
1. Try to resize table.
2. Make a setInterval which updates the table data with new data exactly when resizing

* Version used: 0.7.11
* Browser Name and version: Chrome/Mozilla
* Operating System and version (desktop or mobile): Windows

**Comment by KamranAsif** [comment] 2017-04-06 13:56
Can you create a jsfiddle reproducing this issue?

What happens if you just omit isColumnResizing from your props?

**Comment by KamranAsif** [comment] 2017-04-20 16:19
Closing due to no follow up. If you can post a jsfiddle reproducing this issue, please reopen.

**Closed by KamranAsif** 2017-04-20 16:19 UTC
