### ISSUE TITLE
Scroll bar speed for reorderable columns

### ISSUE THREAD

**Issue by CosminIonascu** [schrodinger/fixed-data-table-2#41] opened 2016-08-04 12:14 UTC
## Current Behavior
When I tray to reorder my column the speed of the scrolling bar is very slow,.

## Possible Solution
It think  will be better if the speed value of the scrolling bar is passed by props.

**Comment by KamranAsif** [comment] 2016-08-04 13:03
The slowdown is probably due to your grid performance more than anything else.
Do you have shouldComponentUpdate speedup enabled in your cells? 

Here is a good readup: http://benchling.engineering/performance-engineering-with-react/

**Comment by gcazaciuc** [comment] 2016-08-04 16:58
same issue here with text only columns. the scroll works super fast but the problem is that if you have many columns, when you drag one of them to the edges ofthe table the scroll moves incredibly slow. it's not really a perf issue but the fact that scroll speed seemsto be hardcoded to 15 px within the table. i believethe scroll velocity should take into account the number of columns and/or be able to pass it by props.

**Comment by KamranAsif** [comment] 2016-08-04 17:30
@gcazaciuc Here is a screencast of our grid using this feature: https://streamable.com/b9bf
I honestly thought it was too fast. 

Feel free to put up a PR to pass the speed via props. We won't be filing this as a bug though.

**Comment by KamranAsif** [comment] 2016-09-15 17:41
Closing this since there is no follow up

**Closed by KamranAsif** 2016-09-15 17:41 UTC
Labels: wontfix
