### ISSUE TITLE
Tabbing between columns horizontally scrolls only that row

### ISSUE THREAD

**Issue by Powerade** [schrodinger/fixed-data-table-2#370] opened 2018-12-13 12:23 UTC
On version: 0.8.16
When tabbing  between columns, to a point where the table scrolls horizontally, the row that is being changed is scrolled while the rest of the table remains in the same place.

Like this:
![bug2](https://user-images.githubusercontent.com/36645390/49938440-d0d46300-fed1-11e8-89b8-c8ca3ce49f6e.gif)

## Your Environment
* Version used: 0.8.16
* Browser Name and version: Chrome latest
* Operating System and version (desktop or mobile): mac desktop
* Link to your project: https://github.com/Powerade/fixed-data-table-2-bugs/tree/horizontal-scroll-tab-bug

**Comment by wcjordan** [comment] 2018-12-13 17:46
Unfortunately this is a known issue and a duplicate of #152 (& #149).  Those issues describe this in more detail as well as a possible solution.  I'd accept a PR for that solution, but I believe it would be a fair amount of work (although there are some POCs you could build on).

For our application, we've worked around this instead by making our cells spans by default and only making them inputs when clicked.  We also prevent inputs from scrolling off screen, either by locking scroll while a cell is being edited or exiting edit mode when a cell scrolls off screen.

I'm going to close as a duplicate, but feel free to continue the conversation on #152

**Closed by wcjordan** 2018-12-13 17:46 UTC
