### ISSUE TITLE
Row heights are not evaluated when table is re-rendered - scrollbar is missing

### ISSUE THREAD

**Issue by 3cooper** [schrodinger/fixed-data-table-2#9] opened 2016-06-05 13:24 UTC
My table has dynamic row heights.  When I change the height of a cell and re-render the table, the scrolling on the table is broken.  If I expand the same row again, scrolling is restored.
## Expected Behavior

I would expect that after re-rendering the table that the scrolling would work.
## Current Behavior

The row expands but the scrollbar is removed which prevents scrolling.
## Possible Solution

It appears that _calculateState() is not getting the actual row heights from the rowHeightGetter methods when it calls

var scrollContentHeight = this._scrollHelper.getContentHeight()

At this point it is getting the height of the rows by checking the rowHeight property on the table. I see in _calculateState() there are other calls that eventually call this._scrollHelper._updateHeightsInViewport() to properly get height.
## Steps to Reproduce (for bugs)

https://jsfiddle.net/3cooper/9dayaac8/
## Context

This prevents me from using this table in a solution that we have designed around it.
## Your Environment
- Version used:  6.1
- Browser Name and version: Chrome 50
- Operating System and version (desktop or mobile):  Desktop OS X 10.11.4
- Link to your project:  It is private.

**Comment by KamranAsif** [comment] 2016-06-06 18:14
The scoller is getting rendered before the rows are.
The app then updates its content height after render, but doesn't trigger and update on itself. 

Might want to take this opportunity to correct data flow from scroll helper..

**Comment by KamranAsif** [comment] 2017-04-06 14:07
Marking this as a duplicate of https://github.com/schrodinger/fixed-data-table-2/issues/25

**Closed by KamranAsif** 2017-04-06 14:07 UTC
Labels: bug
