### ISSUE TITLE
Table Height Grow Not working Dynamically 

### ISSUE THREAD

**Issue by kamaldlk** [schrodinger/fixed-data-table-2#308] opened 2018-03-26 16:24 UTC
Hi, I have created a table while adding row table height want to grow automatically based on the row count. I'm trying to do dynamic row height It's not getting grow Please Help me on this.

![screen shot 2018-03-26 at 9 52 20 pm](https://user-images.githubusercontent.com/9652523/37918902-02cc337a-3140-11e8-83cb-9d8aa14b1dae.png)
![screen shot 2018-03-26 at 9 52 03 pm](https://user-images.githubusercontent.com/9652523/37918903-02fdfa04-3140-11e8-8a45-b4f9032d2857.png)

**Comment by wcjordan** [comment] 2018-03-26 16:55
Please fill out our issue template.  I will be unable to assist with the current details.  Thank you.

I'm closing for now, but please re-open if you can provide all the requested details from the template and a reproduction in a JsFiddle or CodePen

**Closed by wcjordan** 2018-03-26 16:55 UTC

**Comment by kamaldlk** [comment] 2018-03-26 18:28
Hi sorry for incomplete details here sample app please check it : https://codesandbox.io/s/6n073j7p1k


## Expected Behavior
need to grow table height based on the number of rows.

## Current Behavior
Not growing table height based on no of rows

## Possible Solution
height need to give dynamically 

## Steps to Reproduce (for bugs)
https://codesandbox.io/s/6n073j7p1k

**Comment by wcjordan** [comment] 2018-03-26 20:03
From you codesandbox it looks like you're setting the table height to always be 100px
 ```
<Table 
        rowsCount={this.props.data.allRowIds.length}
        rowHeight={50}
        headerHeight={50}
        width={800}
        **height={100}**
        subRowHeightGetter={this.subRowHeightGetter}
        rowExpanded={this.getExpandedRow}
      >
```

You should set that based on the height you want to table to take up on screen
